### ISSUE TITLE
I2C external compass on Crius AIO Pro V1.0 runnning V3.0.1 RC3

### ISSUE THREAD

**Issue by Guido68** [MegaPirateNG/ardupilot-mpng#120]
Hi, 

I want to disable the internal compass and use a HMC5883L as a external compass on my Crius AIO Pro V1.0 board.

Can someone describe me how to make the proper adjustments in het Arduino Sketch so that I can use the external compass?

Thanks in advance,

Guido

**Comment by ralenekov** [comment]
Found in the release notes of R3B:
"Added ability to disable internal compass (to use external) in AP_IntertialSensor_MPU6000_I2C.cpp"

#define DISABLE_INTERNAL_MAG

**Comment by Guido68** [comment]
Should I include the ccp-file in the sketch?

Van: ralenekov [mailto:notifications@github.com] 
Verzonden: vrijdag 14 maart 2014 10:45
Aan: MegaPirateNG/ardupilot-mpng
CC: Guido68
Onderwerp: Re: [ardupilot-mpng] I2C external compass on Crius AIO Pro V1.0 runnning V3.0.1 RC3 (#120)

Found in the release notes of R3B:
"Added ability to disable internal compass (to use external) in AP_IntertialSensor_MPU6000_I2C.cpp"

#define DISABLE_INTERNAL_MAG

**Comment by ralenekov** [comment]
It is included already. Just remove the comment.

**Comment by Guido68** [comment]
Sorry, uncommented it and uploaded the new sketch to the board. Still 
uses the compass from the board, not the external one.

ralenekov schreef op 14-3-2014 11:31:

**Comment by wengwah** [comment]
You have to erase and reset to factory default after uploading. Please get external compass in the correct orientation. By the way, you dont realy need ext compass. I had reverted back to the onboard compass now.

**Comment by smurfy** [comment]
@Guido68 Please close this issue if it's resolved, if not please provide feedback if a factory reset worked for you.

I also added the changes needed to disable the internal compass to the documentation.

http://docs.megapirateng.com/documentation/tipsntricks

**Comment by RiC-** [comment]
Was this resolved?  I have the same issue but on a HK Crius AIOP V2 running MPNG 3.0.1 R4. Uncommented #define DISABLE_INTERNAL_MAG line in AP_IntertialSensor_MPU6000_I2C.cpp, erased and reset to factory default in Mission Planner through terminal but the internal compass still seems to work. Using the Quanum LEA-6H GPS with HMC5883L Digital Compass.  Any ideas?

**Comment by Guido68** [comment]
Yes it is resolved...

RiC- schreef op 28-5-2014 7:29:

**Comment by RiC-** [comment]
How'd you end up resolving it? I still can't seem to disable mine...

**Comment by Guido68** [comment]
Did you select manual compass and set ROTATION_ROLL_180 in MP?
Did you upload the right sketch?
Did you run accel in terminal?
All connections soldered in the right order?

After all the inspections, when you turn the external compass, and hold still the crius board, can you see the compass turn in MP?

Good luck!

**Comment by RiC-** [comment]
I've double checked all those things.  If I hold the crius board still and rotate the external compass, the compass does turn in MP. It doesn't seem like a 360 degree rotation however.  If I do the reverse, hold the compass still and turn the crius board the compass in MP also moves. Actually moving the crius seems to be more effective at moving the compass dial in MP.  I'm all out of ideas??

**Comment by DanO83** [comment]
i found a picture on the AeroQuad site: 

http://aeroquad.com/attachment.php?attachmentid=3500&d=1305557748&stc=1

the compass should be mounted upside down with x pointing forward
